server:
  port: 8088
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arvindsinghh/configserver-config
          clone-on-start: true

